name: Deploy to GitHub Pages
  on:
    push:
      branches:
        - main
  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          REACT_APP_TEST: ${{ secrets.REACT_APP_TEST }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_KEY }}
          BRANCH: gh-pages
          FOLDER: dist
